name: Generate code coverage reports

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install .[dev]
      - name: Generate coverage report
        run: ./dev_builder.py test --cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: library-unittests
          verbose: true
